cert-manager:
  base:
    remoteArtifact:
      url: "https://charts.jetstack.io/charts/cert-manager-v1.11.0.tgz"
  renders:
    - workingDirectory: apps/staging/cert-manager
      releaseName: cert-manager
      namespace: cert-manager
    - workingDirectory: apps/production/cert-manager
      releaseName: cert-manager
      namespace: cert-manager
some-package:
  base:
    chart: helm/some-package
  renders:
    - workingDirectory: apps/staging/some-package
      releaseName: some-package
      namespace: some-package
    - workingDirectory: apps/production/some-package
      releaseName: some-package
      namespace: some-package
