albc:
  type: remoteArtifact
  base:
    remoteArtifact:
      url: "https://aws.github.io/eks-charts/aws-load-balancer-controller-1.6.1.tgz"
    includeCrds: true
  renders:
    - workingDirectory: apps/staging/albc
      releaseName: albc
      namespace: albc
    - workingDirectory: apps/production/albc
      releaseName: albc
      namespace: albc
cert-manager:
  type: remoteArtifact
  base:
    remoteArtifact:
      url: "https://charts.jetstack.io/charts/cert-manager-v1.11.0.tgz"
  renders:
    - workingDirectory: apps/staging/cert-manager
      releaseName: cert-manager
      namespace: cert-manager
    - workingDirectory: apps/production/cert-manager
      releaseName: cert-manager
      namespace: cert-manager
some-package:
  type: localChart
  base:
    localChart: 
      directory: helm/some-package
  renders:
    - workingDirectory: apps/staging/some-package
      releaseName: some-package
      namespace: some-package
    - workingDirectory: apps/production/some-package
      releaseName: some-package
      namespace: some-package
ww-gitops:
  type: remoteChart
  base:
    remoteChart:
      chart: oci://ghcr.io/weaveworks/charts/weave-gitops
      version: 4.0.32
  renders:
    - workingDirectory: apps/staging/weave-gitops
      releaseName: ww-gitops
      namespace: weave-gitops
    - workingDirectory: apps/production/weave-gitops
      releaseName: ww-gitops
      namespace: weave-gitops
