cert-manager:
  base:
    artifactUrl: "https://charts.jetstack.io/charts/cert-manager-v1.11.0.tgz"
  renders:
    - workingDirectory: apps/staging/cert-manager
      releaseName: cert-manager
      namespace: cert-manager
    - workingDirectory: apps/production/cert-manager
      releaseName: cert-manager
      namespace: cert-manager
