---
# Source: some-package/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: some-package
  labels:
    helm.sh/chart: some-package-0.1.0
    app.kubernetes.io/name: some-package
    app.kubernetes.io/instance: some-package
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: some-package/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: some-package
  labels:
    helm.sh/chart: some-package-0.1.0
    app.kubernetes.io/name: some-package
    app.kubernetes.io/instance: some-package
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: some-package
    app.kubernetes.io/instance: some-package
---
# Source: some-package/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-package
  labels:
    helm.sh/chart: some-package-0.1.0
    app.kubernetes.io/name: some-package
    app.kubernetes.io/instance: some-package
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: some-package
      app.kubernetes.io/instance: some-package
  template:
    metadata:
      labels:
        helm.sh/chart: some-package-0.1.0
        app.kubernetes.io/name: some-package
        app.kubernetes.io/instance: some-package
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: some-package
      securityContext:
        {}
      containers:
        - name: some-package
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: some-package/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "some-package-test-connection"
  labels:
    helm.sh/chart: some-package-0.1.0
    app.kubernetes.io/name: some-package
    app.kubernetes.io/instance: some-package
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['some-package:80']
  restartPolicy: Never
