---
  name: "tagged-release"
  
  on:
    push:
      tags:
        - "v*"
  
  jobs:
    tagged-release:
      name: "Tagged Release"
      runs-on: "ubuntu-latest"
  
      steps:
      - name: Setup actions
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: "Build"
        run: |
          go build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            render
