---
name: "verify-example"

on:
  push: {}

jobs:
  verify-example:
    name: "Verify Example"
    runs-on: "ubuntu-latest"

    steps:
      - name: Setup actions
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: Render Example
        run: |
          cd example
          find . -name "*.generated.yaml" -type f -delete
          ./scripts/render.sh render.yaml

      - name: Verify Example
        run: git diff --exit-code 
